<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Password input field on the Login page</description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>or-login-password</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type='password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <value>input</value>
      <type>Main</type>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <value>password</value>
      <type>Main</type>
   </webElementProperties>
</WebElementEntity>
