<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Back button on the transfer confirmation screen that returns to the Transfer Funds form</description>
   <name>button_Back</name>
   <tag></tag>
   <elementGuidId>or-transfer-btn-back</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[normalize-space(.)='Back']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <value>button</value>
      <type>Main</type>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <value>Back</value>
      <type>Main</type>
   </webElementProperties>
</WebElementEntity>
