<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Cancel button on the Transfer Funds form that navigates back to the Dashboard</description>
   <name>button_Cancel</name>
   <tag></tag>
   <elementGuidId>or-transfer-btn-cancel</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[normalize-space(.)='Cancel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <value>button</value>
      <type>Main</type>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <value>Cancel</value>
      <type>Main</type>
   </webElementProperties>
</WebElementEntity>
